const Router = require('express')
const router = new Router()
const courseRouter = require('./courseRouter')
const userRouter = require('./userRouter')
const typeRouter = require('./typeRouter')
const formatRouter = require('./formatRouter')
const sheduleRouter = require('./sheduleRouter')
const requestRouter = require('./requestRouter')
const personalRouter = require('./personalRouter')
const documentRouter = require('./documentRouter')
const moduleRouter = require('./moduleRouter')
const optionRouter = require('./optionRouter')
const licenseRouter = require('./licenseRouter')
const serviceRouter = require('./serviceRouter')
const mailRouter = require('./mailRouter')
const typeofserviceRouter = require('./typeofserviceRouter')

router.use('/course', courseRouter)
router.use('/user', userRouter)
router.use('/type', typeRouter)
router.use('/typeofservice', typeofserviceRouter)
router.use('/shedule', sheduleRouter)
router.use('/format', formatRouter)
router.use('/request', requestRouter)
router.use('/personal', personalRouter)
router.use('/document', documentRouter)
router.use('/module', moduleRouter)
router.use('/option', optionRouter)
router.use('/license', licenseRouter)
router.use('/service', serviceRouter)
router.use('/mail', mailRouter)

module.exports = router